# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose
# values do not exceed four million, find the sum of the
# even-valued terms.

class EvenFibNumbers

  def initialize(largest_number)
    @largest_number = largest_number
    @first_term = 0
    @second_term = 1
    @iterator = 0
    @sum = 0
  end

  def find_sum_of_fib_evens_only
    while @iterator <= @largest_number
      @iterator = @first_term + @second_term
      @sum += @iterator if @iterator.even?
      @first_term = @second_term
      @second_term = @iterator
    end
    @sum
  end
end
